package vine.app.message;
//Auto Generate File, Do NOT Modify!!!!!!!!!!!!!!!
import vine.core.net.HOpCode;
public class HOpCodeEx extends HOpCode {
	public static final int FindCalendarList = 11001;
	public static final int FindCalendarListRet = 11002;
	public static final int FindCalendarById = 11003;
	public static final int FindCalendarByIdRet = 11004;
	public static final int AddCalendar = 11005;
	public static final int EditCalendarById = 11006;
	public static final int DeleteCalendarById = 11007;
	public static final int FindCalendarCategoryList = 11008;
	public static final int FindCalendarCategoryListRet = 11009;
	public static final int FindCalendarCategoryById = 11010;
	public static final int FindCalendarCategoryByIdRet = 11011;
	public static final int AddCalendarCategory = 11012;
	public static final int EditCalendarCategoryById = 11013;
	public static final int DeleteCalendarCategoryById = 11014;
	public static final int FindCalendarCommentList = 11015;
	public static final int FindCalendarCommentListRet = 11016;
	public static final int FindCalendarCommentById = 11017;
	public static final int FindCalendarCommentByIdRet = 11018;
	public static final int AddCalendarComment = 11019;
	public static final int DeleteCalendarCommentById = 11020;
	public static final int Enroll = 10001;
	public static final int EnrollRet = 10002;
	public static final int Logout = 10003;
	public static final int UserInfoEdit = 10004;
	public static final int ForgetPassword = 10005;
	public static final int ResetPassword = 10006;
    public static final int GetValidateCode = 10007;

    public static final int AddTopic = 12001;
    public static final int DeleteTopic = 12002;
    public static final int UpdateTopic = 12003;
    public static final int ListPublicTopic = 12004;
    public static final int ListTopicRet = 12005;
    public static final int ListTopicByUid = 12006;
    public static final int ListFriendTopic = 12007;
    public static final int DoPraise = 12008;
    public static final int DoComment = 12009;
    public static final int DoForward = 12010;
    public static final int DoFavorite = 12011;
    public static final int ListFriendRequest = 12012;
    public static final int ListFriendRequestRet = 12013;
    public static final int UpdateFriendRequest = 12014;
    public static final int AddFriend = 12015;
    public static final int DeleteFriend = 12016;
    public static final int ListFriend = 12017;
    public static final int ListFriendRet = 12018;
    public static final int ListNotice = 12019;
    public static final int ListNoticeRet = 12020;
    public static final int UpdateNotice = 12021;
    public static final int DeleteNotice = 12022;
    public static final int AddLetter = 12023;
    public static final int UpdateLetter = 12024;
    public static final int DeleteLetter = 12025;
    public static final int ListLetter = 12026;
    public static final int ListLetterRet = 12027;
    public static final int Topic = 12028;
    public static final int FriendRequest = 12029;
    public static final int Notice = 12030;
    public static final int Letter = 12031;
}
